plugins {
    id 'dev.architectury.loom' version '1.9.428' apply false
    id 'architectury-plugin' version '3.4.161'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
    id "com.modrinth.minotaur" version "2.+" apply false
    id "net.darkhax.curseforgegradle" version "1.1.28" apply false
}

def buildDate = new Date().format("yyyyMMdd")

def modVersion = System.getenv("VERSION") ?: "dev-${buildDate}"

def releaseChannel = [
        "dev-"  : "beta",
        "alpha-": "alpha",
        "beta-" : "beta"
].find { prefix, _ ->
    modVersion.startsWith(prefix)
}?.value ?: "release"

def taskNames = gradle.startParameter.taskNames*.toLowerCase()

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = modVersion
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'
    apply plugin: "com.modrinth.minotaur"
    apply plugin: "net.darkhax.curseforgegradle"

    base {
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.officialMojangMappings()
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    project(":fabric") {
        modrinth {
            token = System.getenv("MODRINTH_TOKEN")
            projectId = "safedisconnect"

            uploadFile = remapJar

            gameVersions = ["1.21.1"]
            loaders = ["fabric"]

            versionNumber = modVersion
            versionType = releaseChannel
        }
    }

    project(":neoforge") {
        modrinth {
            token = System.getenv("MODRINTH_TOKEN")
            projectId = "safedisconnect"

            uploadFile = remapJar

            gameVersions = ["1.21.1"]
            loaders = ["neoforge"]

            versionNumber = modVersion
            versionType = releaseChannel
        }
    }

    tasks.register("publishCurseForge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {

        apiToken = System.getenv("CURSEFORGE_TOKEN")

        def mainFile = upload(1068018, remapJar)

        mainFile.releaseType = releaseChannel
        mainFile.displayName = "SafeDisconnect ${modVersion}"
        mainFile.addGameVersion('1.21.1')
        mainFile.addEnvironment("Client")
    }
    tasks.register("publishAll") {
        dependsOn(
                ":fabric:modrinth",
                ":fabric:publishCurseForge",
                ":neoforge:modrinth",
                ":neoforge:publishCurseForge"
        )
    }
}