name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior here

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Upload screenshots here

  - type: textarea
    attributes:
      label: PC Infomation (if you use phone dont fill this)
      description: |
        - Launcher: [e.g. MultiMC]
        - Minecraft Version: [e.g. 1.19.2]
        - Mod Version: [e.g. 1.0.0]
        - Architecture: [e.g. 32bit]
        - OS: [e.g. Windows 11]
      placeholder: Launcher, Minecraft Version, Mod Version, Architecture

  - type: textarea
    attributes:
      label: Phone Information (If you use pc Dont fill this)
      description: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. Android 8]
        - Launcher: [e.g. Pojav]
        - Mod Version: [e.g. 1.0.0]
        - Minecraft Version: [e.g. 1.19.2]
      placeholder: Device, OS, Launcher, Mod Version, Minecraft Version

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Additional context
      
