name: build
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: build
        run: ./gradlew build
      
      - name: capture build artifacts
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: create release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          TAG_NAME=$(date +%Y%m%d%H%M%S)
          RELEASE_NAME="Release $TAG_NAME"
          gh release create $TAG_NAME ./build/libs/* --title "$RELEASE_NAME" --notes "This Build Is Automated Don't think it work 100%"
